name: CI for POS exam Java and Spring

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main", "feature/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: 'basic'
          dependency-graph: generate-and-submit

      - name: Build with Gradle
        run: ./gradlew --no-daemon --info build
